export interface Medicamento {
  nombre: string;
  presentaciones: string[];
}

export const MEDICAMENTOS: Medicamento[] = [
  { nombre: "Paracetamol", presentaciones: ["500 mg", "1 g", "Gotas 100 mg/mL"] },
  { nombre: "Ibuprofeno", presentaciones: ["200 mg", "400 mg", "600 mg", "800 mg"] },
  { nombre: "Naproxeno", presentaciones: ["250 mg", "500 mg"] },
  { nombre: "Diclofenaco", presentaciones: ["50 mg", "75 mg", "100 mg"] },
  { nombre: "Metamizol (Dipirona)", presentaciones: ["500 mg", "1 g", "Gotas 500 mg/mL"] },
  { nombre: "Ketorolaco", presentaciones: ["10 mg", "30 mg/mL"] },
  { nombre: "Amoxicilina", presentaciones: ["250 mg", "500 mg", "875 mg"] },
  { nombre: "Amoxicilina / Clavulanato", presentaciones: ["500/125 mg", "875/125 mg"] },
  { nombre: "Azitromicina", presentaciones: ["250 mg", "500 mg"] },
  { nombre: "Claritromicina", presentaciones: ["250 mg", "500 mg"] },
  { nombre: "Ciprofloxacino", presentaciones: ["250 mg", "500 mg", "750 mg"] },
  { nombre: "Levofloxacino", presentaciones: ["250 mg", "500 mg", "750 mg"] },
  { nombre: "Metronidazol", presentaciones: ["250 mg", "500 mg"] },
  { nombre: "Trimetoprim / Sulfametoxazol", presentaciones: ["80/400 mg", "160/800 mg"] },
  { nombre: "Doxiciclina", presentaciones: ["100 mg"] },
  { nombre: "Cefalexina", presentaciones: ["250 mg", "500 mg"] },
  { nombre: "Nitrofurantoína", presentaciones: ["100 mg"] },
  { nombre: "Omeprazol", presentaciones: ["10 mg", "20 mg", "40 mg"] },
  { nombre: "Pantoprazol", presentaciones: ["20 mg", "40 mg"] },
  { nombre: "Ranitidina", presentaciones: ["150 mg", "300 mg"] },
  { nombre: "Sucralfato", presentaciones: ["1 g"] },
  { nombre: "Metoclopramida", presentaciones: ["10 mg"] },
  { nombre: "Domperidona", presentaciones: ["10 mg"] },
  { nombre: "Ondansetrón", presentaciones: ["4 mg", "8 mg"] },
  { nombre: "Loperamida", presentaciones: ["2 mg"] },
  { nombre: "Metformina", presentaciones: ["500 mg", "850 mg", "1000 mg"] },
  { nombre: "Glibenclamida", presentaciones: ["5 mg"] },
  { nombre: "Sitagliptina", presentaciones: ["25 mg", "50 mg", "100 mg"] },
  { nombre: "Empagliflozina", presentaciones: ["10 mg", "25 mg"] },
  { nombre: "Insulina glargina", presentaciones: ["100 UI/mL"] },
  { nombre: "Insulina NPH", presentaciones: ["100 UI/mL"] },
  { nombre: "Losartán", presentaciones: ["25 mg", "50 mg", "100 mg"] },
  { nombre: "Valsartán", presentaciones: ["40 mg", "80 mg", "160 mg"] },
  { nombre: "Enalapril", presentaciones: ["2.5 mg", "5 mg", "10 mg", "20 mg"] },
  { nombre: "Ramipril", presentaciones: ["2.5 mg", "5 mg", "10 mg"] },
  { nombre: "Amlodipino", presentaciones: ["2.5 mg", "5 mg", "10 mg"] },
  { nombre: "Nifedipino", presentaciones: ["10 mg", "30 mg", "60 mg"] },
  { nombre: "Metoprolol", presentaciones: ["25 mg", "50 mg", "100 mg"] },
  { nombre: "Atenolol", presentaciones: ["25 mg", "50 mg", "100 mg"] },
  { nombre: "Propranolol", presentaciones: ["10 mg", "20 mg", "40 mg"] },
  { nombre: "Hidroclorotiazida", presentaciones: ["12.5 mg", "25 mg"] },
  { nombre: "Furosemida", presentaciones: ["20 mg", "40 mg"] },
  { nombre: "Espironolactona", presentaciones: ["25 mg", "100 mg"] },
  { nombre: "Atorvastatina", presentaciones: ["10 mg", "20 mg", "40 mg", "80 mg"] },
  { nombre: "Rosuvastatina", presentaciones: ["5 mg", "10 mg", "20 mg", "40 mg"] },
  { nombre: "Simvastatina", presentaciones: ["10 mg", "20 mg", "40 mg"] },
  { nombre: "Ácido acetilsalicílico", presentaciones: ["81 mg", "100 mg", "325 mg", "500 mg"] },
  { nombre: "Clopidogrel", presentaciones: ["75 mg"] },
  { nombre: "Warfarina", presentaciones: ["1 mg", "2.5 mg", "5 mg"] },
  { nombre: "Levotiroxina", presentaciones: ["25 mcg", "50 mcg", "75 mcg", "100 mcg", "125 mcg"] },
  { nombre: "Prednisona", presentaciones: ["5 mg", "10 mg", "20 mg", "50 mg"] },
  { nombre: "Prednisolona", presentaciones: ["5 mg", "15 mg/5 mL"] },
  { nombre: "Dexametasona", presentaciones: ["0.5 mg", "4 mg", "8 mg"] },
  { nombre: "Betametasona", presentaciones: ["0.5 mg", "4 mg/mL"] },
  { nombre: "Loratadina", presentaciones: ["10 mg"] },
  { nombre: "Cetirizina", presentaciones: ["5 mg", "10 mg"] },
  { nombre: "Fexofenadina", presentaciones: ["120 mg", "180 mg"] },
  { nombre: "Salbutamol", presentaciones: ["100 mcg/dosis (inhalador)", "2 mg", "4 mg"] },
  { nombre: "Montelukast", presentaciones: ["4 mg", "5 mg", "10 mg"] },
  { nombre: "Fluticasona", presentaciones: ["50 mcg/dosis", "100 mcg/dosis", "250 mcg/dosis"] },
  { nombre: "Beclometasona", presentaciones: ["50 mcg/dosis", "100 mcg/dosis"] },
  { nombre: "Alprazolam", presentaciones: ["0.25 mg", "0.5 mg", "1 mg"] },
  { nombre: "Diazepam", presentaciones: ["2 mg", "5 mg", "10 mg"] },
  { nombre: "Clonazepam", presentaciones: ["0.5 mg", "1 mg", "2 mg"] },
  { nombre: "Fluoxetina", presentaciones: ["10 mg", "20 mg"] },
  { nombre: "Sertralina", presentaciones: ["25 mg", "50 mg", "100 mg"] },
  { nombre: "Escitalopram", presentaciones: ["5 mg", "10 mg", "20 mg"] },
  { nombre: "Amitriptilina", presentaciones: ["10 mg", "25 mg", "75 mg"] },
  { nombre: "Tramadol", presentaciones: ["50 mg", "100 mg"] },
  { nombre: "Morfina", presentaciones: ["10 mg", "30 mg"] },
  { nombre: "Gabapentina", presentaciones: ["100 mg", "300 mg", "400 mg"] },
  { nombre: "Pregabalina", presentaciones: ["25 mg", "50 mg", "75 mg", "150 mg"] },
  { nombre: "Carbamazepina", presentaciones: ["100 mg", "200 mg", "400 mg"] },
  { nombre: "Ácido valproico", presentaciones: ["250 mg", "500 mg"] },
  { nombre: "Aciclovir", presentaciones: ["200 mg", "400 mg", "800 mg"] },
  { nombre: "Fluconazol", presentaciones: ["50 mg", "100 mg", "150 mg", "200 mg"] },
  { nombre: "Vitamina D3", presentaciones: ["1000 UI", "2000 UI", "5000 UI"] },
  { nombre: "Ácido fólico", presentaciones: ["0.4 mg", "1 mg", "5 mg"] },
  { nombre: "Hierro (Sulfato ferroso)", presentaciones: ["300 mg"] },
  { nombre: "Calcio + Vitamina D", presentaciones: ["500 mg + 200 UI", "1000 mg + 400 UI"] },
  { nombre: "Vitamina B12 (Cianocobalamina)", presentaciones: ["500 mcg", "1000 mcg"] },
  { nombre: "Magnesio", presentaciones: ["200 mg", "400 mg"] },
  { nombre: "Zinc", presentaciones: ["5 mg", "10 mg", "20 mg"] },
];

export function buscarMedicamento(query: string): Medicamento[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase().trim();
  return MEDICAMENTOS.filter((m) => m.nombre.toLowerCase().includes(q)).slice(0, 10);
}

export const TODOS_LOS_NOMBRES = MEDICAMENTOS.map((m) => m.nombre);
